# Site settings
author: J. Lebron
title: Lebron Does Tech
header-img: img/home-bg.png
email: janislebron@gmail.com
copyright_name: J. Lebron
description: > # this means to ignore newlines until "baseurl:"
  Defeating the Odds
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: janislebron
github_username:  janislebron

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
